[package]
edition = "2021"
name = "aerostream"
version = "0.2.0"

[[bin]]
name = "aerostream"

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
env_logger = "0.10.0"
leb128 = "0.2.5"
libipld = {version = "0.16.0", features = ["serde-codec"]}
log = "0.4.19"
serde = {version = "1.0.164", features = ["derive"]}
serde_json = "1.0.99"
serde_yaml = "0.9.22"
tungstenite = {version = "0.19.0", features = ["rustls-tls-webpki-roots"]}
ureq = {version = "2.7.1", features = ["json"]}
